Repository betagouv/pix, pull requests merged in 2018-02, with the labels that each got.

#671 [#671] [FEATURE] Récupérer les date de début et de fin de certification dans le CSV des résultats (US-1027).
  api/lib/domain/services/certification-service.js
  api/package-lock.json
  api/package.json
  api/scripts/get-results-certifications.js
Labels: [Func] Changes validated, [Tech] Changes done

#678 [#678] [CLEANUP]Suppression de la table 'scenarios' qui n'était plus utilisée (US-1089)
  api/db/migrations/20180212111049_delete_scenario_table.js
  api/lib/domain/models/data/scenario.js
  api/tests/acceptance/application/assessment-controller-get-solutions_test.js
Labels: [Tech] Changes done

#676 [#676] [CLEANUP] Nettoyage de l'algo CAT (US-1074).
  api/lib/cat/answer.js
  api/lib/cat/assessment.js
  api/lib/cat/challenge.js
  api/lib/cat/course.js
  api/lib/infrastructure/adapters/assessment-adapter.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/tests/unit/cat/assessment_test.js
  api/tests/unit/cat/challenge_test.js
  api/tests/unit/cat/course_test.js
  api/tests/unit/infrastructure/adapters/assessment-adapter_test.js
Labels: [Func] Changes validated, [Tech] Changes done, [Tech] Review asked

#681 [#681] Adding ID-Pix and campaign code when sharing profile with PRO (1085)
  live/app/components/share-profile.js
  live/app/templates/components/share-profile.hbs
  live/tests/integration/components/share-profile-test.js
  live/tests/unit/components/share-profile-test.js
Labels: [Func] Review asked, [Tech] Review asked

#677 [CLEANUP] [#677] Utilisation de la nouvelle table Airtable des acquis (US-1025).
  api/lib/domain/models/Skill.js
  api/lib/domain/services/assessment-service.js
  api/lib/infrastructure/repositories/skill-repository.js
  api/lib/infrastructure/serializers/airtable/challenge-serializer.js
  api/package-lock.json
  api/package.json
  api/tests/acceptance/application/assessment-controller-get-adaptive-correct_test.js
  api/tests/acceptance/application/assessment-controller-get-adaptive_test.js
  api/tests/acceptance/application/assessment-controller-get_test.js
  api/tests/unit/domain/services/assessment-service_test.js
  api/tests/unit/domain/services/user-service_test.js
  api/tests/unit/infrastructure/repositories/skill-repository_test.js
Labels: [Func] Changes validated, [Tech] Review asked

#684 [#684] [FEATURE] Changement du texte dans le partage de profil pour les PRO (US-1086).
  live/app/components/share-profile.js
  live/app/templates/components/share-profile.hbs
  live/tests/unit/components/share-profile-test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#683 [#683] [CLEANUP] Remise en place de test front skippés (US-1093)
  live/mirage/config.js
  live/mirage/routes/get-answer-by-challenge-and-assessment.js
  live/mirage/routes/post-assessments.js
  live/mirage/scenarios/default.js
  live/tests/acceptance/certification-course-test.js
Labels: [Tech] Changes validated

#686 [#686] [CLEANUP] Suppression de routes et API endpoints obsolètes (US-1090).
  api/lib/application/challenges/challenge-controller.js
  api/lib/application/challenges/index.js
  api/tests/unit/application/challenges/challenge-controller_test.js
  api/tests/unit/application/challenges/index_test.js
  live/app/router.js
  live/app/routes/courses.js
  live/app/templates/courses.hbs
  live/tests/unit/routes/courses-test.js
Labels: [Func] Changes validated, [Func] Review asked, [Tech] Review asked

#682 [#682] [FEATURE] Récupérer toutes les informations d'un certification (US-1068).
  api/lib/domain/services/assessment-rating-service.js
  api/lib/domain/services/certification-service.js
  api/scripts/get-results-certifications-old.js
  api/tests/acceptance/application/session-controller_test.js
  api/tests/unit/domain/services/assessment-rating-service_test.js
  api/tests/unit/domain/services/certification-service_test.js
Labels: [Func] Changes validated, [Tech] Review asked

#690 [#690] [CLEANUP] Suppression de l'email dans le jeton d'accès JWT (US-1098).
  api/lib/domain/services/token-service.js
  api/tests/acceptance/application/authentication-controller-save_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#687 [#687] [FEATURE] Adapter la colonne "Numero Etudiant" en fonction du type de l'organisation prescripteure ("SUP", "SCO", "PRO") (US-1087).
  api/lib/application/organizations/index.js
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/models/Organization.js
  api/lib/domain/services/organization-service.js
  api/lib/infrastructure/converter/snapshots-csv-converter.js
  api/lib/infrastructure/data/organization.js
  api/lib/infrastructure/repositories/competence-repository.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/package-lock.json
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/services/organization-service_test.js
  api/tests/unit/infrastructure/converter/snapshots-csv-converter_test.js
  api/tests/unit/infrastructure/models/organization_test.js
  api/tests/unit/infrastructure/repositories/competence-repository_test.js
  api/tests/unit/infrastructure/repositories/organization-repository_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#689 [#689] [TECH] Ajout de données pour les review-apps (US-1095).
  api/app.json
  api/db/seeds/data/answers.js
  api/db/seeds/data/assessments.js
  api/db/seeds/data/certification-challenges.js
  api/db/seeds/data/certification-courses.js
  api/db/seeds/data/marks.js
  api/db/seeds/data/organizations.js
  api/db/seeds/data/snapshots.js
  api/db/seeds/data/users.js
  api/db/seeds/seed.js
  api/db/seeds/users.js
  api/scripts/seed_review_app.sh
  api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/mark-repository_test.js
Labels: [Func] Review asked, [Tech] Review asked

#680 [#680] [BUGFIX] Gestion de la casse pour les emails (US-1069).
  api/db/seeds/data/users.js
  api/lib/application/authentication/authentication-controller.js
  api/lib/application/challenges/challenge-controller.js
  api/lib/application/organizations/organization-controller.js
  api/lib/application/passwords/password-controller.js
  api/lib/application/users/user-controller.js
  api/lib/domain/models/User.js
  api/lib/domain/services/token-service.js
  api/lib/infrastructure/repositories/user-repository.js
  api/lib/infrastructure/serializers/jsonapi/user-serializer.js
  api/tests/acceptance/application/assessment-controller-get_test.js
  api/tests/acceptance/application/assessment-controller-post_test.js
  api/tests/acceptance/application/authentication-controller-save_test.js
  api/tests/acceptance/application/feedback-controller_test.js
  api/tests/acceptance/application/follower-controller_test.js
  api/tests/acceptance/application/password-controller_test.js
  api/tests/acceptance/application/snapshot-controller_test.js
  api/tests/acceptance/application/users-controller-get-profile_test.js
  api/tests/acceptance/application/users-controller-save_test.js
  api/tests/integration/infrastructure/repositories/user-repository_test.js
  api/tests/unit/application/answers/answer-controller_test.js
  api/tests/unit/application/authentication/authentication-controller_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/application/passwords/password-controller_test.js
  api/tests/unit/application/preHandlers/user-existence-verification_test.js
  api/tests/unit/application/users/user-controller_test.js
  api/tests/unit/domain/models/bookshelf-user_test.js
  api/tests/unit/domain/models/profile_test.js
  api/tests/unit/domain/services/profile-service_test.js
  api/tests/unit/domain/services/solution-service-function-revalidate_test.js
  api/tests/unit/domain/services/token-service_test.js
  api/tests/unit/domain/services/user-service_test.js
  api/tests/unit/infrastructure/models/session_test.js
  api/tests/unit/infrastructure/models/user_test.js
  api/tests/unit/infrastructure/repositories/answer-repository_test.js
  api/tests/unit/infrastructure/repositories/user-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/profile-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
Labels: [Func] Changes validated, [Tech] Review asked
