Repository betagouv/pix, pull requests merged in 2018-03, with the labels that each got.

#692 [#692] Ajout d'un lien sur Trello vers la RA automagiquement (US-1100)
  .circleci/config.yml
  scripts/trello/comment_with_review_app_url.sh
Labels: [Func] Changes validated, [Tech] Review asked

#696 [#696] [BUGFIX] Correction du bug des résultats pas affichés dans le bon ordre en production (US-1054)
  api/lib/infrastructure/repositories/assessment-repository.js
  api/tests/integration/infrastructure/repositories/assessment-repository_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#691 [#691] [FEATURE] Restriction des accès aux informations de l'endpoint API GET api/organizations (US-1091)
  api/lib/application/organizations/organization-controller.js
  api/lib/domain/services/organization-service.js
  api/lib/infrastructure/repositories/organization-repository.js
  api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/integration/infrastructure/repositories/organization-repository_test.js
  api/tests/unit/application/organizations/organization-controller_test.js
  api/tests/unit/domain/models/organization_test.js
  api/tests/unit/domain/services/organization-service_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#695 [#695] Mise à jour des informations utilisateur + contexte dans la table certification courses (US-1029).
  api/db/migrations/20180216153505_add_user_details_and_rejection_reason_to_certification_courses.js
  api/lib/application/certificationCourses/certification-course-controller.js
  api/lib/application/certificationCourses/index.js
  api/lib/domain/services/certification-course-service.js
  api/lib/infrastructure/data/certification-course.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
  api/lib/infrastructure/serializers/jsonapi/certification-serializer.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/application/session-controller_test.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/application/certificationCourses/certification-course-controller_test.js
  api/tests/unit/application/certificationCourses/index_test.js
  api/tests/unit/domain/services/certification-course-service_test.js
  api/tests/unit/infrastructure/models/certification-course_test.js
  api/tests/unit/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
Labels: [Func] Changes validated, [Tech] Review asked

#700 [#700] [TECH] Renommage des routes d'administration des certif (US-1116).
  api/lib/application/certificationCourses/index.js
  api/scripts/get-results-certifications-old.js
  api/scripts/get-results-certifications.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/unit/application/certificationCourses/index_test.js
Labels: [Func] Review asked, [Tech] Changes validated

#702 [#702] [BUGFIX] Correction des anciens assessments avec un pixScore à 0 (US-1115).
  api/db/batchTreatment.js
  api/db/migrations/20180306151846_add_type_to_all_assessments.js
  api/db/migrations/20180306164441_remove-score-and-level-for-bugged-assessments.js
  api/db/seeds/data/assessments.js
  api/lib/domain/models/Assessment.js
  api/lib/domain/services/assessment-rating-service.js
  api/scripts/fill-score-level.js
  api/tests/unit/domain/models/assessment_test.js
  api/tests/unit/domain/services/assessment-rating-service_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#701 [#701] [BUGFIX] Correction du bug de recalcul du résultat d'une certification (US-1101).
  api/lib/domain/services/certification-service.js
  api/tests/unit/domain/services/certification-service_test.js
Labels: [Func] Review asked, [Tech] Review asked

#708 [#708] [TECH] Mise à jour de la version de momentJS (US-1124)
  api/package-lock.json
  api/package.json
  api/scripts/fill-score-level.js
  api/scripts/get-results-certifications.js
  api/tests/acceptance/application/answer-controller-find_test.js
  api/tests/acceptance/application/answer-controller-get_test.js
  api/tests/acceptance/application/answer-controller-save_test.js
  api/tests/acceptance/application/answer-controller-update_test.js
  api/tests/acceptance/application/authentication-controller-save_test.js
  api/tests/acceptance/application/feedback-controller_test.js
  api/tests/acceptance/application/organization-controller_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/authentication-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/password-reset-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/snapshot-serializer_test.js
Labels: [Func] Changes validated, [Tech] Review asked

#705 [#705] Réparation du script de suppression des utilisateurs (US-1120)
  api/lib/application/sessions/session-controller.js
  api/scripts/delete-user.js
  api/tests/unit/script/delete-user_test.js
Labels: [Func] Review asked, [Tech] Changes validated

#713 [#1094] Ouverture de la route /api/assessments/{id}/solutions/{answerId} pour l'env de preview
  api/lib/application/assessments/index.js
  api/tests/acceptance/application/assessment-controller-get-solutions_test.js
Labels: [Func] Review asked, [Tech] Changes validated

#715 [#715] [FEATURE] Code départ pour les certifications (US-1117).
  api/db/migrations/20180315164634_add-column-access-code-on-sessions.js
  api/db/migrations/20180315164647_add-column-session-id-on-certifications.js
  api/lib/application/courses/course-controller.js
  api/lib/application/courses/index.js
  api/lib/application/preHandlers/access-session.js
  api/lib/application/sessions/session-controller.js
  api/lib/domain/models/Session.js
  api/lib/domain/services/certification-service.js
  api/lib/domain/services/session-code-service.js
  api/lib/domain/services/session-service.js
  api/lib/infrastructure/repositories/session-repository.js
  api/lib/infrastructure/serializers/jsonapi/session-serializer.js
  api/package.json
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/integration/infrastructure/repositories/session-repository_test.js
  api/tests/unit/application/courses/course-controller_test.js
  api/tests/unit/application/courses/index_test.js
  api/tests/unit/application/preHandlers/access-session_test.js
  api/tests/unit/application/session/session-controller_test.js
  api/tests/unit/domain/services/certification-service_test.js
  api/tests/unit/domain/services/session-code-service_test.js
  api/tests/unit/domain/services/session-service_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
  live/app/components/certification-code-validation.js
  live/app/models/course.js
  live/app/router.js
  live/app/routes/certifications/start.js
  live/app/styles/app.scss
  live/app/styles/components/_certification-code-validation.scss
  live/app/styles/pages/_certification-start.scss
  live/app/templates/certification-course.hbs
  live/app/templates/certifications/start-error.hbs
  live/app/templates/certifications/start.hbs
  live/app/templates/components/certification-code-validation.hbs
  live/package-lock.json
  live/tests/acceptance/certification-course-test.js
  live/tests/unit/components/certification-code-validation-test.js
  live/tests/unit/routes/certification-course-test.js
  live/tests/unit/routes/certifications/start-test.js
  package-lock.json
  package.json
Labels: [Func] Review asked, [Tech] Changes done

#717 [#717] [FEATURE] Importation des données de certifications à partir d'un csv (US-1052).
  api/lib/application/certificationCourses/certification-course-controller.js
  api/lib/domain/services/certification-course-service.js
  api/package-lock.json
  api/package.json
  api/scripts/import-certifications-from-csv.js
  api/tests/acceptance/application/certification-course-controller_test.js
  api/tests/acceptance/scripts/file_with_bad_extension.html
  api/tests/acceptance/scripts/import-certifications-from-csv_test.js
  api/tests/acceptance/scripts/valid-certifications-test-file.csv
  api/tests/unit/scripts/delete-user_test.js
  api/tests/unit/scripts/get-results-certifications_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#718 [#718] Correction du bug sur le calcul des résultats de certification (US-1131)
  api/lib/domain/models/Answer.js
  api/lib/domain/services/answer-service.js
  api/lib/domain/services/certification-service.js
  api/lib/infrastructure/adapters/assessment-adapter.js
  api/lib/infrastructure/data/answer.js
  api/lib/infrastructure/repositories/answer-repository.js
  api/package-lock.json
  api/tests/integration/infrastructure/repositories/answer-repository_test.js
  api/tests/unit/domain/models/answer_test.js
  api/tests/unit/domain/services/answer-service_test.js
  api/tests/unit/domain/services/assessment-service_test.js
  api/tests/unit/domain/services/certification-service_test.js
  api/tests/unit/infrastructure/adapters/assessment-adapter_test.js
  api/tests/unit/infrastructure/models/answer_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#719 [#719] [FEATURE] Ajout des infos utilisateurs dans l'endpoint api/admin/certifications/:id (US-1103).
  api/lib/domain/services/certification-service.js
  api/lib/infrastructure/repositories/certification-course-repository.js
  api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js
  api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/domain/services/certification-service_test.js
  api/tests/unit/infrastructure/repositories/certification-course-repository_test.js
  api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
Labels: [Func] Changes validated, [Tech] Changes validated

#724 [#724] Amélioration du style du bouton Se Déconnecter (US-1139)
  live/app/styles/app.scss
  live/app/styles/components/_challenge-actions.scss
  live/app/styles/components/_user-logged-menu.scss
  live/app/styles/globals/_buttons.scss
  live/app/templates/components/user-logged-menu.hbs
Labels: [Func] Review asked, [Tech] Review asked

#709 [#709] [Bugfix] Ne poste pas de commentaire Trello sur une branche de release (US-1130)
  .circleci/config.yml
Labels: [Tech] Review asked

#726 [#726] Ajout d'une fiche de poste (US-1188)
  live/public/recrutements/charge-de-projet-e-education.pdf
Labels: [Func] Changes validated, [Tech] Changes validated
